# Generated by Django 5.1.4 on 2024-12-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_recommend',
        ),
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
