# Generated by Django 5.1.4 on 2024-12-20 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5, message="rating can't be more than Five!"), django.core.validators.MinValueValidator(0, message="rating can't be less than Zero!")]),
        ),
    ]
