# Generated by Django 5.1.4 on 2024-12-31 07:49

import products.upload_method
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_managers_alter_comment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=products.upload_method.product_image_upload, verbose_name='Product Image'),
        ),
    ]
