# Generated by Django 5.1.4 on 2025-01-02 10:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image_alter_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
