# Generated by Django 5.1.4 on 2025-01-23 13:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 1, 23, 13, 15, 22, 586668, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 1, 23, 13, 15, 22, 586668, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.discount'),
        ),
    ]
